### ISSUE TITLE
Research: Elasticsearch (OpenSearch). How to use, purpose and results

### ISSUE THREAD

**Issue by savin000** [VSU-CS-MCS/recommendations-service#5]

**Comment by MaGixPro** [comment]
OpenSearch позволяет легко получать, защищать, искать, агрегировать, просматривать и анализировать данные для различных сценариев использования, таких как анализ журналов, поиск приложений, корпоративный поиск и многое другое. С OpenSearch вы получаете выгодный продукт со 100 % открытым исходным кодом, который можно использовать, изменять, расширять, монетизировать и перепродавать по своему усмотрению. [Количество партнеров проекта OpenSearch постоянно увеличивается](https://opensearch.org/partners/). Они предлагают различные услуги, такие как профессиональная поддержка, расширенные возможности и управляемые услуги OpenSearch. Проект OpenSearch по-прежнему будет предоставлять безопасный высококачественный набор инструментов для поиска и аналитики с [большим выбором](https://github.com/orgs/opensearch-project/projects/1) новых и инновационных функциональных возможностей.

Elasticsearch
Преимущества Elasticsearch
Выгодное соотношение цены и времени
Elasticsearch предлагает простые API на основе REST и легкий HTTP-интерфейс, а также использует документы JSON без схем, благодаря чему проще приступить к работе и быстро создавать приложения для различным примеров использования.
Высокая производительность
Распределенная система Elasticsearch позволяет параллельно обрабатывать большие объемы данных, мгновенно подбирая наилучшее соответствие к запросу.
Бесплатные инструменты и модули
Elasticsearch встроен в Kibana, популярный инструмент визуализации и составления отчетов. Доступна также интеграция с Beats и Logstash, при этом исходные данные легко преобразовывать и загрузить в кластер Elasticsearch. Можно использовать ряд подключаемых модулей Elasticsearch с открытым исходным кодом, таких как языковые анализаторы и механизмы рекомендаций, для более широкой функциональности ваших приложений.
Операции в режиме, близком к реальному времени
Выполнение операций в Elasticsearch, таких как чтение или запись данных, обычно занимает менее секунды. Это позволяет использовать его в таких примерах, где необходимо реагировать почти в режиме реального времени, например для мониторинга приложений и обнаружения аномалий.
Простая разработка приложений
Elasticsearch обеспечивает поддержку различных языков, включая Java, Python, PHP, JavaScript, Node.js, Ruby и многие другие.


Цены Amazon OpenSearch
Поисковая система с открытым исходным кодом: цены на сервис Amazon OpenSearch – Amazon Web Services

[[9] Углубленный анализ исходного кода elasticsearch - загрузки компонента плагина. - Русские Блоги (russianblogs.com)](https://russianblogs.com/article/49481202844/)


SQL и NO-SQL
Для чего нужны базы данных

● собирать и хранить данные в виде таблиц;
● изменять их содержимое и структуру;
● объединять данные и выполнять вычисления;
● защищать и распределять доступ.

Обычно базы данных делят на два вида:

•	Нереляционные — NoSQL.
•	Реляционные — SQL.
SQL-базы данных используют структурированный язык запросов (SQL) для управления данными, для их обработки, хранения, обновления, удаления.


NoSQL — это сокращение от not only SQL (не только SQL). Этим термином обозначают базу данных любого типа, которая хранит информацию не так, как хранят её РСУБД. NoSQL-базы данных отлично подходят для многих современных приложений, которым нужны гибкие, масштабируемые, высокопроизводительные базы данных, обладающие широким набором функциональных возможностей. Среди таких приложений — проекты из мобильной и веб-сферы, компьютерные игры. Возможности NoSQL-баз данных позволяют таким проектам давать своим пользователям наилучшие впечатления от работы с ними.

Основные виды баз данных NoSQL

Базы данных типа «ключ-значение» (key-value database) — это простейшая БД NoSQL, где у каждой записи есть ключ, а так же — значение, связанное с этим ключом.

Документоориентированные базы данных (document-oriented database) — так называются базы данных, каждая запись которых представляет собой документ, содержащий поля и значения. 

Колоночные базы данных (wide-column database) — в таких БД для хранения данных используются таблицы, строки и столбцы (колонки). Но, в отличие от реляционных баз данных, имена и форматы столбцов в одной и той же таблице могут отличаться.

Графовые базы данных (graph database) — это БД, которые хранят данные в узлах и рёбрах графов. Обычно данные о неких сущностях хранят в узлах, а сведения об отношениях между узлами хранят в рёбрах. Графовые базы данных созданы специально для того, чтобы хранить сведения о взаимоотношениях между сущностями и чтобы работать с этими сведениями.
Сравнение SQL и NoSQL

Масштабирование
SQL: масштабируется вертикально. То есть — путём увеличения производительности за счёт использования более мощных серверов. SQL-БД сложнее масштабировать, чем NoSQL-БД.
NoSQL: масштабируется горизонтально. То есть — путём добавления дополнительных узлов к уже существующим, использующимся узлам. Это упрощает масштабирование — при необходимости можно быстро как повысить, так и понизить мощность системы. Это, кроме того, означает, что владелец NoSQL-БД может увеличивать её мощность практически неограниченно.
Гибкость
SQL: эти БД не дают пользователю особой гибкости. Для работы с ними сначала надо спроектировать схему базы данных. А если в систему нужно внести какие-то изменения, например — добавить к записям новое свойство/столбец, придётся добавлять этот столбец к каждой строке. Это — ресурсозатратная и длительная операция.
NoSQL: эта технология даёт гораздо больше гибкости, чем её «старший брат». Здесь нет фиксированного количества столбцов, NoSQL-БД очень легко адаптируются к новым схемам данных. Программисту, кроме того, не нужно заранее создавать схему БД. Это ускоряет подготовку к работе систем, основанных на NoSQL. Правда, использование этой технологии может вылиться в дополнительные затраты времени в том случае, если для некоего проекта понадобятся достаточно жёсткие схемы данных.
Структура данных
SQL: данные хранятся в таблицах. Каждая сущность имеет собственную таблицу, они связаны друг с другом с использованием реляционных механизмов. Отсюда и термин — «реляционная система управления базами данных».
NoSQL: данные хранятся с использованием большего количества подходов, чем при использовании SQL-БД. В частности, доступны такие способы хранения данных, как база данных типа «ключ-значение», документоориентированная база данных, колоночная база данных, графовая база данных.
Набор требований, обеспечивающий сохранность данных
SQL: эти БД следуют требованиям [ACID](https://www.mongodb.com/basics/acid-transactions). ACID — это сокращение от Atomicity (атомарность), Consistency (согласованность), Isolation (изолированность) и Durability (надёжность).
NoSQL: эти БД следуют требованиям теоремы [CAP](https://www.geeksforgeeks.org/the-cap-theorem-in-dbms/). CAP расшифровывается как Consistency (согласованность), Availability (доступность) и Partition Tolerance (устойчивость к разделению).
Поддержка и сообщество
SQL: так как история SQL начинается в 1970-х, вокруг этой идеологии работы с данными сложилось обширное сообщество, готовое помочь тем, у кого возникают сложности. Наработан большой опыт применения SQL в самых разных проектах. Но при этом многие диалекты SQL являются либо собственностью неких компаний, либо связаны с отдельными большими компаниями, что означает некоторую их изоляцию.
NoSQL: так как БД NoSQL гораздо моложе БД SQL, они отличаются меньшим сообществом, для которого характерна большая разобщённость из-за разных подходов, использующихся в разных NoSQL-базах данных. При этом такие БД пользуются поддержкой опенсорс-сообщества, у каждой из них есть детальное руководство, описывающее особенности её использования.
Сценарии использования
SQL: SQL-базы данных обычно предназначены для решения широкого круга задач. Они используются в достаточно старых системах, в приложениях, нуждающихся в строгом контроле данных, там, где нужно выполнять большие и сложные запросы. Такие базы данных, кроме того, часто используются в финансовом секторе, так как транзакции, проводимые в таких БД, строго соответствуют требованиям ACID.
NoSQL: NoSQL-базы данных тоже можно назвать универсальными, но они по-настоящему раскрываются в приложениях, которые работают с разными источниками данных, имеющих различную структуру. Это могут быть IoT-приложения, игры и прочее подобное. Если рассмотреть варианты использования разных типов NoSQL-БД, о которых мы говорили выше, то получится следующее:
•	Документоориентированные базы данных: широкий круг задач.
•	Базы данных типа «ключ-значение»: обработка больших объёмов данных, где применяются простые запросы на поиск данных (например — управление сессиями в крупномасштабных системах).
•	Колоночные базы данных: обработка больших объёмов данных с предсказуемыми шаблонами запросов (работа с журналами, IoT).
•	Графовые базы данных: анализ и просмотр отношений между связанными данными (обнаружение мошенничеств, рекомендательные системы).

  Elasticsearch как NoSQL
отличия
Отсутствие транзакций

Lucene, на основе которой построен Elasticsearch, имеет поддержку транзакций, хотя Elasticsearch при этом не имеет транзакций в привычном понимании этого слова. То есть откатить отправленный документ или работать с группой документов атомарно невозможно. 


Гибкость схемы данных

В Elasticsearch не надо указывать схему данных заранее. Достаточно отправить JSON-документ, и сервер сам выполнит необходимые операции, чтобы определить его тип. Это хорошо работает, когда речь идет о числовых и логических типах данных и о временных метках. Для строк будет использоваться стандартный анализатор, который подходит для базовых операций.



Отношения и ограничения

Elasticsearch — документоориентированная база данных: весь пул объектов, по которому вы собираетесь делать поиск, должен быть проиндексирован, а значит, перед индексацией документы должны быть денормализованы. Это увеличивает производительность извлечения (так как вам не требуются join-запросы), требует больше дискового пространства (из-за хранения избыточной информации), но при этом обеспечить консистентность и актуальность данных (любое измерение затрагивает все документы, содержащие изменяемый объект) становится сложнее. Однако это идеальный вариант, если документ необходимо сохранить один раз, а читать его будут много раз.


Другими словами, при работе с документоориентированными базами данных, как Elasticsearch, проектируется маппинг, и документы хранятся в оптимальном для поиска и извлечения виде.




Надежность или устойчивость к падениям (robustness)

База данных должна быть надежной, особенно если она является основным хранилищем информации. В идеале, в ней должна быть предусмотрена возможность отмены ресурсоемкого запроса и, конечно, она не должна перестать работать, пока вы сами этого не захотите.

К сожалению, Elasticsearch, как и компоненты, из которых он построен, в настоящее время плохо обрабатывают OutOfMemory-ошибки. Более подробно мы остановимся на этом в статье «[Elasticsearch in Production, OutOfMemory-Caused Crashes](https://www.found.no/foundation/elasticsearch-in-production/#outofmemory-caused-crashes)». Важно обеспечить Elasticsearch достаточным объемом памяти и быть осторожным перед запуском запросов с новыми неизвестными требованиями к памяти на производственном кластере.

Хотя это, вероятно, будет исправлено по мере развития Elasticsearch, следует помнить, что Elasticsearch создавался для высокой скорости, и предполагалось, что оперативной памяти на сервере будет в избытке.


Распределенность


Elasticsearch невероятно прост в использовании и подходит для тех, кто только начинает свою работу с распределенными системами, хоть они и достаточно сложны. Подробнее мы рассмотрим этот момент в следующих разделах.



Безопасность


Elasticsearch не имеет возможности для идентификации или авторизации. Вам надо учитывать, что любой пользователь может подключиться к вашему Elasticsearch-кластеру и получить права суперпользователя, особенно если разрешена поддержка скриптов.


Резюме

Безусловно, Elasticsearch, можно использовать как основное хранилище, если описанные выше ограничения не являются для вас проблемой. Хороший пример — [Logstash](http://logstash.net/), фантастический инструмент для управления логами. Он хранит их в Elasticsearch и имеет возможность хранить их в другом месте. Логи пишутся один раз, а читаются при этом много. Если нет обновлений, то нет и необходимости в транзакциях, обеспечении целостности и др.

А как насчет таких систем, как Postgres, которые поддерживают [полнотекстовый поиск](http://www.postgresql.org/docs/current/static/textsearch.html) и ACID-транзакции (другие примеры — полнотекстовые возможности MySQL, MongoDB, Riak и т. Д.

Читать об этом подробнее 
[Elasticsearch как NoSQL база данных / Хабр (habr.com)](https://habr.com/ru/post/222765/)

Использование Elasticsearch в Spring Data
[Введение в Spring Data Elasticsearch | Baeldung (turbopages.org)](https://translated.turbopages.org/proxy_u/en-ru.ru.8d8c121f-63ee16f9-365fd6ca-74722d776562/https/www.baeldung.com/spring-data-elasticsearch-tutorial)

[spring-projects/spring-data-elasticsearch: Provide support to increase developer productivity in Java when using Elasticsearch. Uses familiar Spring concepts such as a template classes for core API usage and lightweight repository style data access. (github.com)](https://github.com/spring-projects/spring-data-elasticsearch?ysclid=le72bv5i1h690484926)
