### ISSUE TITLE
Research: architecture for Python + neural network service

### ISSUE THREAD

**Issue by savin000** [VSU-CS-MCS/recommendations-service#7]

**Comment by Mr-Keltt** [comment]
![Image](https://user-images.githubusercontent.com/66189075/219956393-85516dff-15a4-4f10-90cf-ea1570c92e08.png)

**Comment by Mr-Keltt** [comment]
![Image](https://user-images.githubusercontent.com/66189075/219961352-f93fff4c-f54c-494b-98fa-d7dc461ec924.png)

**Comment by savin000** [comment]
Very nice explanation. We will think more about overall architecture on the next week (I do not really understand why do we need separated DB service here. User service can use it's own DB without any additional layers), but ok, that's enough for starting point
